apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: module.create
  title: Create Module
  description: Creates a module with its IaC repository
spec:
  owner: user:guest
  type: system
  parameters:
    - title: Let's create your new module
      required:
        - module
        - description
      properties:
        module:
          title: Name
          type: string
          description: Unique name of the module
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Some fancy description of what your module does
        owner:
          title: GitHub owner
          type: string
          description: The organization, user or project that this repo will belong to
  steps:
    - name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          module: ${{ parameters.module }}
          description: ${{ parameters.description }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: Repository for module ${{ parameters.module }}
        repoUrl: github.com?repo=Md.${{ parameters.module }}&owner=${{ parameters.owner }} 
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
